### ISSUE TITLE
Quelques demandes pour mon nouveau poste

### ISSUE THREAD

**Issue by nathalieroy19** [motrec-international-inc/IT-HelpDesk#10]
Salut, 

je ne semble pas avoir accèes au P:. Serait-ce possible de me donner accès svp. 

Il faudrait aussi installer UPS Worldship sur mon poste de travail.

Ma souris sans fil ne fonctionne pas  (j'ai changer 3 fois de souris et aucune d'elle fonctionne)

Merci! :)

**Comment by motrecaisabella** [comment]
all done except installing the zebra printers
