### ISSUE TITLE
genius-expédition non facturée

### ISSUE THREAD

**Issue by kfortin77** [motrec-international-inc/IT-HelpDesk#17]
Bonjour, Carina semble avoir remarqué qu'il y a beaucoup de vielles expéditions non facturées. Pourrais-tu nous faire une extraction Excel de ces expéditions avec des $ et date afin qu'on puisse faire des vérifications sur les montants les plus importants. Voir Carina sur les éléments que devraient comporter cette liste afin qu'on puisse demander à quelqu'un de retracer si on voit aussi cet expédition dans le logiciel de UPS ou fedex.

Merci

**Comment by motrecaisabella** [comment]
Bonjour Karine -

J'ai créé un ticket chez Genius pour voir quoi faire avec cette situation. Je te dirais qu'il y a plusieurs erreures dans Genius qui ont été causé par les usagés dans le passé et je n'ai pas de réponse rapide pour remédier à cette problématique autre que de faire l'exercise manuelle de passer un travers de chacun des expéditions et décortiquer chaque causes. 

J'attends toujours de voir ce que Genius me dira et pour ton information j'ai un problème similaire mes cette fois si au niveau des commandes client qui sont suggèré à être expédier mais dans plusieurs cas ces commandes ont déjà été expédier. Il ne semble pas y avoir eu un bon control dans le passé chez Motrec et ces choses nous hante maintenant alors j'essaie de voir ce qui peut-être fait mais comme je l'ai dis c'est pas une problématique qui peut facilement être rêglé.

Merci,

Ai
