### ISSUE TITLE
EMPTY FOLDERS

### ISSUE THREAD

**Issue by nathalieroy19** [motrec-international-inc/IT-HelpDesk#18]
Hey, Carina for Nathalie here hehe, 

so now that we have access to the P:, it seems Nathalie does not have access to the documents inside the folders. Nic was saying something about her not being added to the sales team??

thanks!

**Comment by motrecaisabella** [comment]
you will need to tell me which folder(s).

**Comment by nathalieroy19** [comment]
All of these, see 2 screen shots below. All the folders included.
[cid:image001.png@01D53D62.C259C4D0]
[cid:image002.png@01D53D62.C259C4D0]

[cid:image011.jpg@01D53D62.C265ABB0]
Nathalie Roy
Coordonnatrice aux ventes et service à la clientèle
Sales & Customer Service Ccordinator

+1 819.846.2010, ext. 254
nroy@motrec.com<mailto:nroy@motrec.com>
MOTREC INTERNATIONAL INC.
4685, boul. de Portland
Sherbrooke, Québec  J1L 0J1
CANADA
T. +1 866.846.3558
F. 819.846.3050
www.motrec.com<http://www.motrec.com/>
[Facebook]<https://www.facebook.com/MotrecIntl>[Twitter]<https://twitter.com/MotrecIntl>[Youtube]<https://www.youtube.com/user/motrecintl>[Linkedin]<https://www.linkedin.com/company/motrec>[Instagram]<https://instagram.com/motrec/>


De : Anthony Isabella <notifications@github.com>
Envoyé : 18 juillet 2019 11:19
À : motrec-international-inc/IT-HelpDesk <IT-HelpDesk@noreply.github.com>
Cc : Nathalie Roy <nroy@motrec.com>; Author <author@noreply.github.com>
Objet : Re: [motrec-international-inc/IT-HelpDesk] EMPTY FOLDERS (#18)


you will need to tell me which folder(s).

**Comment by motrecaisabella** [comment]
can you resend the screenshot? i can not see them. you may have to go directly to the ticket in github and copy paste the images there instead of replying to the email.

**Comment by motrecaisabella** [comment]
i added you to the same security group as carinna, simply log out of your windows session and relog in again. keep me posted.

**Comment by nathalieroy19** [comment]
Hi Anthony,
Everything works fine.

Thanks, have a great weekend.


[cid:image008.jpg@01D53E47.91AC83A0]
Nathalie Roy
Coordonnatrice aux ventes et service à la clientèle
Sales & Customer Service Ccordinator

+1 819.846.2010, ext. 254
nroy@motrec.com<mailto:nroy@motrec.com>
MOTREC INTERNATIONAL INC.
4685, boul. de Portland
Sherbrooke, Québec  J1L 0J1
CANADA
T. +1 866.846.3558
F. 819.846.3050
www.motrec.com<http://www.motrec.com/>
[Facebook]<https://www.facebook.com/MotrecIntl>[Twitter]<https://twitter.com/MotrecIntl>[Youtube]<https://www.youtube.com/user/motrecintl>[Linkedin]<https://www.linkedin.com/company/motrec>[Instagram]<https://instagram.com/motrec/>


De : Anthony Isabella <notifications@github.com>
Envoyé : 18 juillet 2019 15:56
À : motrec-international-inc/IT-HelpDesk <IT-HelpDesk@noreply.github.com>
Cc : Nathalie Roy <nroy@motrec.com>; Author <author@noreply.github.com>
Objet : Re: [motrec-international-inc/IT-HelpDesk] EMPTY FOLDERS (#18)


i added you to the same security group as carinna, simply log out of your windows session and relog in again. keep me posted.
