### ISSUE TITLE
Intranet non fonctionnel

### ISSUE THREAD

**Issue by gdeslauriers** [motrec-international-inc/IT-HelpDesk#19]
![intanet prob](https://user-images.githubusercontent.com/52081107/61476019-17070e80-a95a-11e9-8384-e67b768f86fd.png)

**Comment by gdeslauriers** [comment]
Seulement pour une job... le reste est fonctionnel.

**Comment by motrecaisabella** [comment]
did you try closing your browser and restarting it?
