### ISSUE TITLE
EXPÉDITIONS

### ISSUE THREAD

**Issue by CJBRENNEMAN** [motrec-international-inc/IT-HelpDesk#7]
Hey, 

I just found an old expedition from March 2018 and realized it was never invoiced and it dawned on me that there must be a ton of uninvoiced expeditions. 

I was wondering if you could find a way to isolate all uninvoiced expeditions, so I can give those a look on my end :) 

Thanks!

**Comment by motrecaisabella** [comment]
if you go to your customer invoices, there is a button in the top left corner = invoice by shipping. this list shows all shipments not invoiced. 
![image](https://user-images.githubusercontent.com/52080866/60736351-a527d180-9f24-11e9-9866-92b0ced94c76.png)
![image](https://user-images.githubusercontent.com/52080866/60736363-b40e8400-9f24-11e9-9f97-81fe79618b7b.png)

**Comment by CJBRENNEMAN** [comment]
Good morning,

No lol, that’s what I thougt too, but the only expedition showing was invoiced this morning and I have a few expeditions that have not been invoiced that don’t appear on this list, unfortunately.

Thank you and have a great day!

[https://htmlsigs.s3.amazonaws.com/logos/files/000/210/132/landscape/motrec-signature.png]<http://www.motrec.com/>
Carina Julie Brenneman
Parts Sales Executive /
Gestionnaire des ventes de pièces
819-846-2010, Ext. 224
cjbrenneman@motrec.com <mailto:cjbrenneman@motrec.com>
MOTREC INTERNATIONAL INC.
4685 Portland Boulevard
Sherbrooke, Quebec, J1L 0J1
CANADA
T. 1-866-846-3558
F. 819-846-3050
www.motrec.com<http://www.motrec.com/>
[https://s3.amazonaws.com/htmlsig-assets/grey/facebook.png]<https://www.facebook.com/MotrecIntl>[https://s3.amazonaws.com/htmlsig-assets/grey/twitter.png]<https://twitter.com/MotrecIntl>[https://s3.amazonaws.com/htmlsig-assets/grey/youtube.png]<https://www.youtube.com/user/motrecintl>[https://s3.amazonaws.com/htmlsig-assets/grey/linkedin.png]<https://www.linkedin.com/company/motrec>[https://s3.amazonaws.com/htmlsig-assets/grey/instagram.png]<https://instagram.com/motrec/>
