### ISSUE TITLE
Ouverture des PDF très lent

### ISSUE THREAD

**Issue by JeepDubois** [motrec-international-inc/IT-HelpDesk#8]
Si Adobe n'est pas déjà ouvert, un PDF peut prendre jusqu'à deux minutes à ouvrir...

**Comment by motrecaisabella** [comment]
Je vais regarder avec Kezber car j'ai ton poste et celui de Martin qui est lent. Je te reviens dès que Kezber me donne des nouvelles.

**Comment by JeepDubois** [comment]
Super! Mais je suis sur que ce ne sont pas seulement le mien et celui à Martin qui le fait. En tout cas, vérifie si nous sommes les seuls.

De : Anthony Isabella <notifications@github.com>
Envoyé : 10 juillet 2019 12:05
À : motrec-international-inc/IT-HelpDesk <IT-HelpDesk@noreply.github.com>
Cc : Jean-Pascal Dubois <jpdubois@motrec.com>; Author <author@noreply.github.com>
Objet : Re: [motrec-international-inc/IT-HelpDesk] Ouverture des PDF très lent (#8)


Je vais regarder avec Kezber car j'ai ton poste et celui de Martin qui est lent. Je te reviens dès que Kezber me donne des nouvelles.

**Comment by motrecaisabella** [comment]
i opened a ticket with kezber... 

Numéro / Number | 45510
-- | --

**Comment by motrecaisabella** [comment]
Can you try this :

Edit> Preferences > Security (enhanced) and deselect "Enable protected mode at start up" and click OK. (very important to click ok)
