### ISSUE TITLE
Générer les DXF de mise en plan avec l'Intranet

### ISSUE THREAD

**Issue by JeepDubois** [motrec-international-inc/IT-HelpDesk#9]
Après avoir fini mes mises en plan, je génère mes PDF/DXF/Step/zip avec l'intranet. Cependant, je crois que mon poste est mal configuré puisque lorsque je génère les DXF, seul le contour de mes pièce est conservé: mes enlèvements de matière et mes gravures de pli disparaissent.

**Comment by motrecaisabella** [comment]
Salut JP - 

Je vais regarder mais on a aucune documentation des configurations qui doivent être fait. Est-ce que tu as regardé avec d'autres gars avec toi si eu on le même problème ajd ou bien s'il sont tous ok? JL a d'autres problèmes avec l'Intranet

**Comment by JeepDubois** [comment]
Peut-être que Claude saurait quel est le problème. Et ça fait à peu près une semaine que j’ai eu ce problème là et j’ai découvert ce matin qu’on pouvait créer des coupons de support IT fac je m’en suis servi 😊

De : Anthony Isabella <notifications@github.com>
Envoyé : 10 juillet 2019 12:04
À : motrec-international-inc/IT-HelpDesk <IT-HelpDesk@noreply.github.com>
Cc : Jean-Pascal Dubois <jpdubois@motrec.com>; Author <author@noreply.github.com>
Objet : Re: [motrec-international-inc/IT-HelpDesk] Générer les DXF de mise en plan avec l'Intranet (#9)


Salut JP -

Je vais regarder mais on a aucune documentation des configurations qui doivent être fait. Est-ce que tu as regardé avec d'autres gars avec toi si eu on le même problème ajd ou bien s'il sont tous ok? JL a d'autres problèmes avec l'Intranet

**Comment by motrecaisabella** [comment]
Can I close this?

**Comment by JeepDubois** [comment]
Voici la solution:

![image](https://user-images.githubusercontent.com/52748178/60989266-81450100-a313-11e9-9300-aa9d1d0b88fa.png)

![image](https://user-images.githubusercontent.com/52748178/60989311-a174c000-a313-11e9-8267-f419c4a100ff.png)

![image](https://user-images.githubusercontent.com/52748178/60993678-ef41f600-a31c-11e9-82f8-56ce67583119.png)

Puis, appuyer sur OK et enregsitrer en temps que DXF.
